'use client';
import {useEffect,useState} from 'react';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import {usePreferences} from '../preferences';
import {money,statuses} from '@/lib/product';
export default function AdminPanel(){const {t,money,date}=usePreferences();const [orders,setOrders]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(''),[cursor,setCursor]=useState<string|null>(null);
async function load(append=false){setLoading(true);setError('');try{const r=await fetch('/api/admin/orders'+(append&&cursor?'?before='+encodeURIComponent(cursor):''));const d=await r.json() as {error?:string;orders:any[];nextCursor:string|null};if(!r.ok)throw new Error(d.error);setOrders(v=>append?[...v,...d.orders]:d.orders);setCursor(d.nextCursor)}catch(e){setError((e as Error).message||t("অর্ডার আনা যায়নি।"))}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
function change(ref:string,key:string,value:string){setOrders(v=>v.map(o=>o.reference===ref?{...o,[key]:value}:o))}
async function save(o:any){setSaving(o.reference);setError('');setMessage('');try{const r=await fetch('/api/admin/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference:o.reference,status:o.status,paymentStatus:o.payment_status})});const d=await r.json() as {error?:string;orders:any[];nextCursor:string|null};if(!r.ok)throw new Error(d.error);setMessage(o.reference+t(" — পরিবর্তন সংরক্ষিত হয়েছে।"))}catch(e){setError((e as Error).message)}finally{setSaving('')}}
return <div className="admin-panel"><button className="outline-btn" disabled={loading} onClick={()=>load()}>{t("অর্ডার রিফ্রেশ করুন")}</button>{error&&<p role="alert" className="error-banner">{t(error)}</p>}<p role="status">{message}{loading?t("অর্ডার আনা হচ্ছে…"):''}</p>{!loading&&!orders.length&&<p>{t("এখনো কোনো অর্ডার নেই।")}</p>}<div className="admin-orders">{orders.map(o=><article key={o.reference} className="admin-order"><div className="history-top"><strong>{o.reference}</strong><span>{money(o.total)} {o.is_demo?t("· পরীক্ষামূলক"):''}</span></div><dl><dt>{t("নাম")}</dt><dd>{o.name}</dd><dt>{t("মোবাইল")}</dt><dd><a href={'tel:'+o.phone}>{o.phone}</a></dd><dt>{t("ঠিকানা")}</dt><dd>{o.address}</dd><dt>{t("এলাকা")}</dt><dd>{o.area==='bangladesh'?t('সারা বাংলাদেশ'):o.area==='dhaka'?t("ঢাকার ভিতরে"):t("ঢাকার বাইরে")}</dd><dt>{t("সময়")}</dt><dd>{date(o.created_at)}</dd><dt>{t("ক্যাম্পেইন")}</dt><dd>{Object.entries(JSON.parse(o.campaign||'{}')).map(([k,v])=>k+': '+v).join(' · ')||t("সরাসরি")}</dd></dl><div className="admin-controls"><label>{t("অর্ডারের অবস্থা")}<Select value={o.status} onValueChange={v=>change(o.reference,'status',v)}><SelectTrigger aria-label={o.reference+t(" অর্ডারের অবস্থা")}><SelectValue/></SelectTrigger><SelectContent>{Object.entries(statuses).map(([k,v])=><SelectItem key={k} value={k}>{t(v)}</SelectItem>)}</SelectContent></Select></label><label>{t("পেমেন্ট")}<Select value={o.payment_status} onValueChange={v=>change(o.reference,'payment_status',v)}><SelectTrigger aria-label={o.reference+t(" পেমেন্ট")}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unpaid">{t("বকেয়া")}</SelectItem><SelectItem value="paid">{t("পরিশোধিত")}</SelectItem></SelectContent></Select></label><button className="btn" disabled={!!saving} onClick={()=>save(o)}>{saving===o.reference?t("সংরক্ষণ হচ্ছে…"):t("সংরক্ষণ করুন")}</button></div></article>)}</div>{cursor&&<button className="outline-btn" disabled={loading} onClick={()=>load(true)}>{t("আগের অর্ডারগুলো দেখুন")}</button>}</div>}

