'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {usePreferences} from '../preferences';
import ColourFields from '../colour-fields';
import {english} from '@/lib/translations';
import {defaultContent,palettes,paletteNames,isPalette,parseVideo,videoUrl,validDocument,imageSlots,sectionKeys,type SiteContent,type ContentDocument} from '@/lib/site-content';
const tabs=['রং ও ভিডিও','পণ্যের তথ্য','ছবি','লেখা','সেকশন ও SEO'];
const imageNames:Record<string,string>={hero:'প্রধান ছবি',checkout:'চেকআউটের ছবি',product:'অর্ডার সারাংশের ছবি',gallery0:'গ্যালারি — সামনে',gallery1:'গ্যালারি — ভেতর',gallery2:'গ্যালারি — পেছন',gallery3:'গ্যালারি — বিস্তারিত',gallery4:'গ্যালারি — প্যাকেজ',gallery5:'গ্যালারি — বাক্স',gallery6:'গ্যালারি — তথ্য'};
const productNames:Record<string,string>={name:'পণ্যের নাম',model:'মডেল',brand:'ব্র্যান্ডের নাম',price:'অফার মূল্য',regular:'রেগুলার মূল্য',deliveryFee:'সারা বাংলাদেশে ডেলিভারি ফি',phone:'যোগাযোগ নম্বর (+880)',facebook:'Facebook পেজ লিংক',version:'ওয়্যারলেস ভার্সন',battery:'ব্যাটারি'};
const sectionNames:Record<string,string>={details:'বৈশিষ্ট্য',gallery:'ছবির গ্যালারি',video:'ভিডিও',steps:'অর্ডারের ধাপ',faq:'প্রশ্ন ও উত্তর'};
export default function SiteSettings({demo=false,initial=defaultContent}:{demo?:boolean;initial?:SiteContent}){const {t}=usePreferences();const [settings,setSettings]=useState<SiteContent>(initial),[url,setUrl]=useState(videoUrl(initial)),[loadFailed,setLoadFailed]=useState(false),[loading,setLoading]=useState(!demo),[saving,setSaving]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[tab,setTab]=useState(tabs[0]),[query,setQuery]=useState(''),[uploading,setUploading]=useState(''),[dirty,setDirty]=useState(false);
async function load(){setLoading(true);setLoadFailed(false);setError('');try{const r=await fetch('/api/admin/settings');if(!r.ok)throw new Error();const d=await r.json() as {settings:SiteContent};setSettings(d.settings);setUrl(videoUrl(d.settings));setDirty(false)}catch{setLoadFailed(true);setError('সেটিংস আনা যায়নি।')}finally{setLoading(false)}}useEffect(()=>{if(!demo)void load()},[demo]);
useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
function change(next:SiteContent){setSettings(next);setDirty(true);setSaved(false)}function doc(next:ContentDocument){change({...settings,document:next})}
async function save(e:FormEvent){e.preventDefault();if(loadFailed)return;setSaved(false);setError('');if(!parseVideo(url)||!validDocument(settings.document)){setError('তথ্যগুলো যাচাই করুন। সঠিক মূল্য, যোগাযোগ নম্বর ও ভিডিও লিংক দিন।');return}if(demo){setSaved(true);setDirty(false);return}setSaving(true);try{const r=await fetch('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({palette:settings.palette,videoUrl:url,sample:settings.sample,document:settings.document})});const d=await r.json() as {error?:string;settings:SiteContent};if(!r.ok)throw new Error(d.error||'সেটিংস সংরক্ষণ করা যায়নি।');setSettings(d.settings);setSaved(true);setDirty(false)}catch(e){setError((e as Error).message||'সেটিংস সংরক্ষণ করা যায়নি।')}finally{setSaving(false)}}
async function upload(key:string,file:File){setError('');if(file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('JPG, PNG বা WebP ছবি দিন, সর্বোচ্চ ৫ MB।');return}if(demo){setError('ছবি আপলোড করতে অনুমোদিত বিক্রেতা প্যানেল ব্যবহার করুন।');return}setUploading(key);try{const r=await fetch('/api/admin/media',{method:'POST',headers:{'Content-Type':file.type},body:file});const d=await r.json() as {url?:string};if(!r.ok||!d.url)throw new Error();setSettings(v=>({...v,document:{...v.document,images:{...v.document.images,[key]:d.url!}}}));setDirty(true);setSaved(false)}catch{setError('ছবি আপলোড হয়নি। আবার চেষ্টা করুন।')}finally{setUploading('')}}
async function uploadVideo(file:File){setError('');if(demo)return;if(!['video/mp4','video/webm'].includes(file.type)||file.size>20*1024*1024){setError('MP4 বা WebM ভিডিও দিন, সর্বোচ্চ ২০ MB।');return}setUploading('video');try{const response=await fetch('/api/admin/media',{method:'POST',headers:{'Content-Type':file.type},body:file});const data=await response.json() as {url?:string;error?:string};if(!response.ok||!data.url)throw new Error(data.error||'ভিডিও আপলোড হয়নি।');setUrl(data.url);setSettings(v=>({...v,sample:false}));setDirty(true);setSaved(false)}catch(e){setError((e as Error).message)}finally{setUploading('')}}
const document=settings.document,copyKeys=Object.keys(english).filter(k=>!query||k.toLowerCase().includes(query.toLowerCase())||english[k].toLowerCase().includes(query.toLowerCase()));
return <section className="admin-panel site-settings cms"><div className="cms-heading"><div><h2>{t('সাইট সম্পাদনা')}</h2><p className="muted">{t(demo?'এটি নমুনা প্যানেল। এখানকার পরিবর্তন প্রকাশিত সাইটে সেভ হবে না।':'পরিবর্তন করে সেভ করুন। নতুন তথ্য সবার জন্য প্রকাশিত হবে।')}</p></div><a href="/" className="outline-btn" target="_blank" rel="noopener noreferrer">{t('সাইট দেখুন')}</a></div><nav className="cms-tabs" aria-label={t('সম্পাদনার বিভাগ')}>{tabs.map(x=><button type="button" key={x} aria-pressed={tab===x} onClick={()=>setTab(x)}>{t(x)}</button>)}</nav>{loading?<p role="status">{t('সেটিংস আনা হচ্ছে…')}</p>:loadFailed?null:<form onSubmit={save}>
{tab===tabs[0]&&<><label htmlFor="site-palette">{t('ডিফল্ট রং')}</label><div className="palette-grid">{palettes.map(p=><button type="button" key={p} className={'palette-option palette-'+p} aria-pressed={settings.palette===p} onClick={()=>change({...settings,palette:p})}><span className="swatches" aria-hidden="true"><i/><i/><i/></span><span>{t(paletteNames[p])}</span></button>)}</div>{settings.palette==='custom'&&<ColourFields t={t} value={document.design} onChange={design=>doc({...document,design})}/>}<p className="fine">{t('দর্শক নিজে রং বেছে নিলে তাঁর পছন্দটি অগ্রাধিকার পাবে।')}</p><label htmlFor="video-url">{t('Facebook / YouTube ভিডিও লিংক')}</label><input id="video-url" type="text" maxLength={500} value={url} onChange={e=>{setUrl(e.target.value);setSaved(false);setDirty(true)}} required/><label>{t('অথবা সরাসরি ভিডিও আপলোড করুন')}<input type="file" accept="video/mp4,video/webm" disabled={!!uploading||saving||demo} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadVideo(file);e.target.value=''}}/></label><p className="fine">{t('MP4 বা WebM, সর্বোচ্চ ২০ MB। আপলোডের পরে পরিবর্তন সেভ করুন।')}</p>{uploading==='video'&&<p role="status">{t('ভিডিও আপলোড হচ্ছে…')}</p>}<p className="fine">{t('Facebook ভিডিওটি Public হতে হবে। Share লিংকের বদলে মূল ভিডিওর লিংক দিন।')}</p><label className="sample-choice"><input type="checkbox" checked={settings.sample} onChange={e=>change({...settings,sample:e.target.checked})}/>{t('এটি নমুনা ভিডিও')}</label><p className="fine">{t('নিজের পণ্যের ভিডিও দিলে নমুনা চিহ্নটি সরিয়ে সেভ করুন।')}</p></>}
{tab===tabs[1]&&<div className="cms-fields">{Object.entries(productNames).map(([key,label])=><label key={key}>{t(label)}<input type={typeof document.product[key as keyof typeof document.product]==='number'?'number':'text'} min={key==='price'?1:0} max={1000000} maxLength={key==='facebook'?500:120} value={document.product[key as keyof typeof document.product]} onChange={e=>doc({...document,product:{...document.product,[key]:typeof document.product[key as keyof typeof document.product]==='number'?Number(e.target.value):e.target.value}})}/></label>)}</div>}
{tab===tabs[2]&&<div className="cms-images">{imageSlots.map(key=><article key={key}><img src={document.images[key]} alt={t(imageNames[key])}/><label>{t(imageNames[key])}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={!!uploading||demo} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(key,f)}}/></label>{uploading===key&&<p role="status">{t('ছবি আপলোড হচ্ছে…')}</p>}<button type="button" className="text-button" onClick={()=>doc({...document,images:{...document.images,[key]:defaultContent.document.images[key]}})}>{t('আগের ছবি ফিরিয়ে দিন')}</button></article>)}</div>}
{tab===tabs[3]&&<><label htmlFor="copy-search">{t('যে লেখা বদলাবেন সেটি খুঁজুন')}</label><input id="copy-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('যেমন: চশমা, ডেলিভারি, অর্ডার')}/><p className="fine">{t('মূল্য ও পণ্যের নামের বন্ধনীর অংশ রেখে দিন; এগুলো স্বয়ংক্রিয়ভাবে পূরণ হয়।')}</p><div className="cms-copy-list">{copyKeys.map(key=><details key={key}><summary>{key}</summary><label>বাংলা<textarea maxLength={3000} value={document.copy[key]?.bn??key} onChange={e=>doc({...document,copy:{...document.copy,[key]:{bn:e.target.value,en:document.copy[key]?.en??english[key]}}})}/></label><label>English<textarea maxLength={3000} value={document.copy[key]?.en??english[key]} onChange={e=>doc({...document,copy:{...document.copy,[key]:{bn:document.copy[key]?.bn??key,en:e.target.value}}})}/></label><button type="button" className="text-button" onClick={()=>{const copy={...document.copy};delete copy[key];doc({...document,copy})}}>{t('মূল লেখা ফিরিয়ে দিন')}</button></details>)}</div></>}
{tab===tabs[4]&&<><h3>{t('যে সেকশনগুলো দেখাবেন')}</h3>{sectionKeys.map(key=><label className="sample-choice" key={key}><input type="checkbox" checked={document.sections[key]} onChange={e=>doc({...document,sections:{...document.sections,[key]:e.target.checked}})}/>{t(sectionNames[key])}</label>)}<label>{t('পেজের শিরোনাম')}<input maxLength={160} value={document.seo.title} onChange={e=>doc({...document,seo:{...document.seo,title:e.target.value}})}/></label><label>{t('পেজের সংক্ষিপ্ত বিবরণ')}<textarea maxLength={400} value={document.seo.description} onChange={e=>doc({...document,seo:{...document.seo,description:e.target.value}})}/></label></>}
<div className="cms-save"><button className="btn" disabled={saving||!!uploading} type="submit">{t(saving?'সংরক্ষণ হচ্ছে…':demo?'নমুনা পরিবর্তন দেখুন':'পরিবর্তন সেভ করুন')}</button><span className="fine">{dirty?t('পরিবর্তন সেভ করা হয়নি।'):''}</span></div></form>}{error&&<p role="alert" className="error-banner">{t(error)}</p>}{loadFailed&&!loading&&<button className="outline-btn" onClick={load}>{t('আবার চেষ্টা করুন')}</button>}{saved&&<p role="status" className="cms-success">{t(demo?'নমুনা পরিবর্তন গ্রহণ করা হয়েছে। এটি শুধু এই প্যানেলের প্রিভিউ।':'সেটিংস সংরক্ষিত। পণ্যের পাতা রিফ্রেশ করলে দেখা যাবে।')}</p>}</section>}
