'use client';
import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import ColourFields from './colour-fields';
import {colourTokens} from '@/lib/colours';
import {Moon,Sun,Palette as PaletteIcon,Check,X} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {translate,type Language} from '@/lib/translations';
import {palettes,paletteNames,isPalette,type Palette,validColours,type CustomColours,defaultDocument,type ContentDocument} from '@/lib/site-content';
type Theme='light'|'dark';
type Preferences={ready:boolean;language:Language;theme:Theme;palette:Palette;customColours:CustomColours;setCustomColours:(v:CustomColours)=>void;setPalette:(v:Palette|null)=>void;setLanguage:(v:Language)=>void;setTheme:(v:Theme)=>void;t:(v:unknown)=>string;money:(n:number)=>string;date:(v:string)=>string};
const Context=createContext<Preferences|null>(null);
export function PreferencesProvider({children,defaultPalette='ocean',document:content=defaultDocument}:{children:ReactNode;defaultPalette?:Palette;document?:ContentDocument}){
 const [language,setLanguage]=useState<Language>('bn'),[theme,setTheme]=useState<Theme>('light'),[chosenPalette,setPalette]=useState<Palette|null>(null),[loaded,setLoaded]=useState(false),[customColours,setCustomColours]=useState(content.design);const palette=chosenPalette||defaultPalette;
 useEffect(()=>{try{localStorage.removeItem('f06_language');if(localStorage.getItem('f06_theme')==='dark')setTheme('dark');const p=localStorage.getItem('f06_palette');if(isPalette(p))setPalette(p);const colours=JSON.parse(localStorage.getItem('f06_colours')||'null');if(validColours(colours))setCustomColours(colours)}catch{}setLoaded(true)},[]);
 useEffect(()=>{document.documentElement.lang=language;document.documentElement.dataset.theme=theme;document.documentElement.dataset.palette=palette;if(loaded)try{localStorage.setItem('f06_theme',theme);localStorage.setItem('f06_colours',JSON.stringify(customColours));if(chosenPalette)localStorage.setItem('f06_palette',chosenPalette);else localStorage.removeItem('f06_palette')}catch{}},[language,theme,palette,chosenPalette,loaded,customColours]);
 useEffect(()=>{const tokens=colourTokens(customColours,theme==='dark');for(const [key,value] of Object.entries(tokens)){if(palette==='custom')document.documentElement.style.setProperty(key,value);else document.documentElement.style.removeProperty(key)}},[palette,theme,customColours]);
 const t=useCallback((text:unknown)=>(()=>{const key=String(text??'').trim(),custom=content.copy[key];let value=custom?(custom[language]||translate(text,language)):translate(text,language);const p=content.product,m=(n:number)=>'৳'+new Intl.NumberFormat(language==='bn'?'bn-BD':'en-BD').format(n);const vars:Record<string,string>={price:m(p.price),regular:m(p.regular),saving:m(p.regular-p.price),deliveryFee:m(p.deliveryFee),orderTotal:m(p.price+p.deliveryFee),productName:p.name,model:p.model,phone:p.phone};return value.replace(/\{(price|regular|saving|deliveryFee|orderTotal|productName|model|phone)\}/g,(_all,k)=>vars[k]);})(),[language,content]);
 const value=useMemo(()=>({ready:loaded,language,theme,palette,customColours,setCustomColours,setPalette,setLanguage,setTheme,t,money:(n:number)=>'৳'+new Intl.NumberFormat(language==='bn'?'bn-BD':'en-BD').format(n),date:(v:string)=>new Date(v).toLocaleString(language==='bn'?'bn-BD':'en-GB',{dateStyle:'medium',timeStyle:'short'})}),[language,theme,palette,customColours,t,loaded]);
 return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function usePreferences(){const value=useContext(Context);if(!value)throw new Error('Missing preferences provider');return value}
export function PreferenceControls(){const {ready,language,setLanguage,theme,setTheme,palette,setPalette,customColours,setCustomColours,t}=usePreferences();const [open,setOpen]=useState(false);return <div className="preferences" role="group" aria-label={t('ভাষা ও রঙের পছন্দ')}><div className="language-switch"><button disabled={!ready} type="button" lang="bn" aria-pressed={language==='bn'} onClick={()=>setLanguage('bn')}>বাংলা</button><button disabled={!ready} type="button" lang="en" aria-pressed={language==='en'} onClick={()=>setLanguage('en')}>EN</button></div><button disabled={!ready} type="button" className="theme-switch" aria-label={t(theme==='light'?'ডার্ক মোড চালু করুন':'লাইট মোড চালু করুন')} title={t(theme==='light'?'ডার্ক মোড চালু করুন':'লাইট মোড চালু করুন')} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}<span>{t(theme==='light'?'ডার্ক মোড':'লাইট মোড')}</span></button><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button disabled={!ready} type="button" className="palette-trigger" aria-haspopup="dialog" aria-expanded={open} ><PaletteIcon size={18}/>{t('রং')}</button></DialogTrigger><DialogContent showCloseButton={false} className="site-modal palette-modal"><DialogTitle className="modal-title">{t('আপনার পছন্দের রং')}</DialogTitle><DialogDescription className="modal-description">{t('যেকোনো রং বেছে নিন। পছন্দটি শুধু এই ব্রাউজারে থাকবে।')}</DialogDescription><DialogClose className="modal-close" aria-label={t('বন্ধ করুন')}><X size={20}/></DialogClose><div className="palette-grid" role="group" aria-label={t('রঙের সমন্বয়')}>{palettes.map(p=><button className={'palette-option palette-'+p} key={p} type="button" aria-pressed={p===palette} onClick={()=>setPalette(p)}><span className="swatches" aria-hidden="true"><i/><i/><i/></span><span>{t(paletteNames[p])}{p===palette&&<Check size={17}/>}</span></button>)}</div>{palette==='custom'&&<ColourFields t={t} value={customColours} onChange={setCustomColours}/>}<button disabled={!ready} type="button" className="outline-btn" onClick={()=>setPalette(null)}>{t('সাইটের ডিফল্ট রং')}</button><DialogClose className="btn">{t('ঠিক আছে')}</DialogClose></DialogContent></Dialog></div>}
export function LocalizedText({children}:{children:string}){const {t}=usePreferences();return <>{t(children)}</>}
