'use client';
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowUpRight, Headphones, Truck, Glasses, Mic, PackageCheck, ArrowRight, Phone, MessageCircle, Check, Copy, X, ZoomIn, History, RefreshCw, LockKeyhole, Bluetooth, ChevronRight } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose } from '@/components/ui/dialog';

import { PRODUCT as BASE_PRODUCT, money, normalizePhone, statuses, validateOrder, type OrderInput, type PublicConfig, type SavedOrder } from '@/lib/product';
import ProductVideo from './product-video';
import type {SiteContent} from '@/lib/site-content';
import { usePreferences, PreferenceControls } from './preferences';
import { readCampaign, consent, setConsent, pageEvent, viewEvent, checkoutEvent, purchaseEvent } from '@/lib/analytics';


const storageKey='f06_orders_v1';
function loadOrders():SavedOrder[]{try{const list=JSON.parse(localStorage.getItem(storageKey)||'[]');return Array.isArray(list)?list.filter(v=>v&&typeof v.reference==='string'&&/^[a-f0-9]{64}$/.test(v.token)&&Number.isFinite(v.total)).slice(0,30):[]}catch{return []}}
const randomToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(32))).map(v=>v.toString(16).padStart(2,'0')).join('');
async function fingerprint(text:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(v=>v.toString(16).padStart(2,'0')).join('');}


function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description:string;children:ReactNode;wide?:boolean}){const {t}=usePreferences();const lastFocus=useRef<HTMLElement|null>(null);return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent showCloseButton={false} onOpenAutoFocus={()=>{lastFocus.current=document.activeElement as HTMLElement}} className={'site-modal '+(wide?'wide':'')} onCloseAutoFocus={e=>{e.preventDefault();(lastFocus.current?.isConnected && lastFocus.current.tagName!=="BODY" ? lastFocus.current : document.querySelector<HTMLElement>("#checkout button[type=submit]"))?.focus()}}><DialogTitle className="modal-title">{title}</DialogTitle><DialogDescription className="modal-description">{description}</DialogDescription><DialogClose className="modal-close" aria-label={t("বন্ধ করুন")}><X size={21}/></DialogClose>{children}</DialogContent></Dialog>}

export default function Storefront({config,content}:{config:PublicConfig;content:SiteContent}){
const {t,language,money,date}=usePreferences();const product=content.document.product,images=content.document.images,sections=content.document.sections;const PRODUCT={...BASE_PRODUCT,id:product.model,name:product.name,price:product.price,regular:product.regular,phone:product.phone,facebook:product.facebook,whatsapp:'https://wa.me/'+product.phone.replace('+',''),delivery:{bangladesh:product.deliveryFee}};
const photos=[['77767',t("সামনের দিক")],['77768',t("ফ্রেম ও ভেতরের অংশ")],['77769',t("পেছনের দিক")],['77770',t("ফ্রেমের বিস্তারিত")],['77757',t("প্যাকেজে পণ্য")],['77752',t("মূল প্যাকেজিং")],['77755',t("প্যাকেজিংয়ের তথ্য")]] as const;
function whatsapp(order?:SavedOrder){return PRODUCT.whatsapp+'?text='+encodeURIComponent(order?(language==='en'?`Please confirm my order. Reference: ${order.reference}. ${PRODUCT.name} (${PRODUCT.id}), 1 item. Total: ${money(order.total)}. Cash on delivery.`:`আমার অর্ডার কনফার্ম করতে চাই। রেফারেন্স: ${order.reference}। ${PRODUCT.name} (${PRODUCT.id}), ১টি। মোট: ${money(order.total)}। ক্যাশ অন ডেলিভারি।`):t('F-06 Glasses Wireless headset সম্পর্কে জানতে চাই।'));}
 const [photo,setPhoto]=useState(0),[zoom,setZoom]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[policy,setPolicy]=useState<'privacy'|'delivery'|null>(null),[order,setOrder]=useState<SavedOrder|null>(null),[orders,setOrders]=useState<SavedOrder[]>([]),[historyError,setHistoryError]=useState(''),[refreshing,setRefreshing]=useState(''),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState('');
 const [input,setInput]=useState<OrderInput>({name:'',email:'',phone:'',address:'',area:'bangladesh'}),[errors,setErrors]=useState<Record<string,string>>({}),[submitError,setSubmitError]=useState(''),[submitting,setSubmitting]=useState(false),[checkoutVisible,setCheckoutVisible]=useState(false),[consentOpen,setConsentOpen]=useState(false),[storageWarning,setStorageWarning]=useState('');
 const checkout=useRef<HTMLElement>(null), hero=useRef<HTMLElement>(null),campaign=useRef<Record<string,string>>({}),busy=useRef(false),pending=useRef<{hash:string;key:string;token:string}|null>(null);
 const delivery=PRODUCT.delivery.bangladesh,total=PRODUCT.price+delivery;
 const setField=(key:keyof OrderInput,value:string)=>{setInput(v=>({...v,[key]:value}));setErrors(v=>({...v,[key]:''}));};
 const persist=(list:SavedOrder[])=>{setOrders(list);try{localStorage.setItem(storageKey,JSON.stringify(list))}catch{setStorageWarning(t("এই ব্রাউজারে হিস্ট্রি সেভ করা যায়নি। অর্ডার রেফারেন্সটি কপি করে রাখুন।"))}};
 useEffect(()=>{campaign.current=readCampaign();setOrders(loadOrders());let choice=null;try{choice=localStorage.getItem('f06_tracking')}catch{}setConsentOpen(!!config.pixelId&&!choice);void pageEvent(config.pixelId);const observer=new IntersectionObserver(entries=>setCheckoutVisible(entries.some(e=>e.isIntersecting)),{threshold:0});if(checkout.current)observer.observe(checkout.current);const views=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))void viewEvent(config.pixelId,PRODUCT.price,PRODUCT.id)},{threshold:.3});if(hero.current)views.observe(hero.current);return()=>{observer.disconnect();views.disconnect()}},[config.pixelId]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(ctx.registerTool({name:'prepare_f06_checkout',title:t('F-06 অর্ডার প্রস্তুত করুন'),description:'Opens the checkout for nationwide Bangladesh delivery. Does not place an order.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(){checkout.current?.scrollIntoView({behavior:'instant'});return{area:'bangladesh',subtotal:PRODUCT.price,delivery,total,orderPlaced:false}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[t,PRODUCT.price,delivery,total]);
 const allowTracking=(allow:boolean)=>{setConsent(allow);setConsentOpen(false);if(allow){void pageEvent(config.pixelId);if(hero.current&&hero.current.getBoundingClientRect().bottom>0)void viewEvent(config.pixelId,PRODUCT.price,PRODUCT.id)}};
 async function submit(e:FormEvent){e.preventDefault();if(busy.current)return;const next=validateOrder(input);setErrors(next);setSubmitError('');if(Object.keys(next).length){document.getElementById(Object.keys(next)[0])?.focus();return}busy.current=true;setSubmitting(true);try{
 const normalized={...input,name:input.name.trim(),email:input.email.trim().toLowerCase(),phone:normalizePhone(input.phone),address:input.address.trim()};const hash=await fingerprint(JSON.stringify(normalized));let previous=pending.current;try{previous=previous||JSON.parse(sessionStorage.getItem('f06_pending')||'null')}catch{}if(!previous||previous.hash!==hash)previous={hash,key:crypto.randomUUID(),token:randomToken()};pending.current=previous;try{sessionStorage.setItem('f06_pending',JSON.stringify(previous))}catch{}
 const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...normalized,idempotencyKey:previous.key,token:previous.token,campaign:campaign.current}),signal:AbortSignal.timeout(20000)});const data=await response.json() as {order:SavedOrder;error?:string;errors?:Record<string,string>};if(!response.ok){if(data.errors)setErrors(data.errors);throw new Error(data.error||t("অর্ডার জমা দেওয়া যায়নি। আবার চেষ্টা করুন।"))}
 const saved={...data.order,token:previous.token,syncedAt:new Date().toISOString()} as SavedOrder;persist([saved,...loadOrders().filter(v=>v.reference!==saved.reference)].slice(0,30));setOrder(saved);setCopied(false);setCopyError('');void purchaseEvent(config.pixelId,saved);
 }catch(error){setSubmitError(error instanceof Error && !['TimeoutError','TypeError'].includes(error.name)?error.message:t("সংযোগে সমস্যা হয়েছে। আপনার তথ্য আছে—আবার চেষ্টা করুন।"))}finally{busy.current=false;setSubmitting(false)}}
 async function refresh(saved:SavedOrder){setRefreshing(saved.reference);setHistoryError('');try{const response=await fetch('/api/orders/track',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+saved.token},body:JSON.stringify({reference:saved.reference}),signal:AbortSignal.timeout(15000)});const data=await response.json() as {order:SavedOrder;error?:string;errors?:Record<string,string>};if(!response.ok)throw new Error();persist(loadOrders().map(v=>v.reference===saved.reference?{...v,...data.order,syncedAt:new Date().toISOString()}:v));}catch{setHistoryError(t("সর্বশেষ অবস্থা আনা যায়নি। নিচে আগের সংরক্ষিত তথ্য দেখানো হচ্ছে। আবার চেষ্টা করুন।"))}finally{setRefreshing('')}}
 async function copyReference(){if(!order)return;try{await navigator.clipboard.writeText(order.reference);setCopied(true)}catch{const field=document.getElementById('order-reference') as HTMLInputElement;field?.focus();field?.select();setCopyError(t("কপি হয়নি। নির্বাচিত রেফারেন্সটি ম্যানুয়ালি কপি করুন।"))}}
 function openHistory(){setOrders(loadOrders());setHistoryOpen(true)}
 const trackStart=()=>{void checkoutEvent(config.pixelId,PRODUCT.price,PRODUCT.id)};

 return <><a href="#main" className="skip-link">{t("মূল অংশে যান")}</a><div className="topnote">{t("আপনার স্টাইলে নতুন সাউন্ড। ")}<span>{t("ক্যাশ অন ডেলিভারি সুবিধা")}</span></div>
 <header className="header wrap"><a className="brand" href="/" aria-label={t("Glasses Wireless headset — প্রথম পাতা")}><Glasses size={31}/><span>{product.brand}<span>{PRODUCT.name} · {PRODUCT.id}</span></span></a><nav aria-label={t("প্রধান নেভিগেশন")}><a href="#details">{t("পণ্যের বিবরণ")}</a><button className="text-button desktop-history" onClick={openHistory}>{t("আমার অর্ডার")}</button><a className="btn small" href="#checkout" onClick={trackStart}>{t("অর্ডার করুন ")}<ArrowUpRight size={17}/></a></nav><PreferenceControls/></header>
 <main id="main"><section className="hero wrap" ref={hero}><div className="hero-copy"><p className="eyebrow">{PRODUCT.id} / {PRODUCT.name}</p><h1>{t("চশমা পরুন।")}<br/><em>{t("প্রিয় গানও শুনুন।")}</em></h1><p className="lead">{t("কালো ফ্রেমের পরিচিত লুকে ওয়্যারলেস অডিও। F-06-এ স্টাইল আর আপনার পছন্দের সুর, একসঙ্গে।")}</p><div className="price"><strong>{t("{price}")}</strong><del>{t("{regular}")}</del><span>{t("{saving} সাশ্রয়")}</span></div><a className="btn" href="#checkout" onClick={trackStart}>{t("{price}-এ অর্ডার করুন ")}<ArrowUpRight size={20}/></a><p className="fine">{t("ডেলিভারি চার্জ প্রযোজ্য · পণ্য হাতে পেয়ে মূল্য পরিশোধ")}</p><div className="hero-delivery"><span><Truck size={16}/>{t('সারা বাংলাদেশে ডেলিভারি')}: {money(delivery)}</span><span>{t('ডেলিভারিসহ মোট')}: {money(total)}</span></div></div><div className="hero-art"><div className="art-label"><span>{t("স্টাইল। সাউন্ড। একসঙ্গে।")}</span><span>F-06</span></div><img src={images.hero} alt={t("F-06 কালো ফ্রেমের গ্লাসেস ওয়্যারলেস হেডসেটের বাস্তব ছবি")} width="1600" height="900" fetchPriority="high"/><div className="art-bottom"><span><Headphones size={18}/>{t(" ওয়্যারলেস স্টেরিও")}</span><span>{t("আসল পণ্যের ছবি")}</span></div></div></section>
 <div className="trust wrap"><span><Glasses/>{t(" কালো ফ্রেমের মিনিমাল লুক")}</span><span><Headphones/>{t(" ওয়্যারলেস অডিও")}</span><span><Truck/>{t(" ক্যাশ অন ডেলিভারি")}</span></div>
 {sections.details&&<section id="details" className="wrap section benefits"><div><p className="eyebrow">{t("আপনার প্রতিদিনের সঙ্গে")}</p><h2>{t("চশমার পরিচিত রূপে,")}<br/>{t("অডিওর নতুন অভিজ্ঞতা।")}</h2><p className="muted section-intro">{t("একটি গ্যাজেট, পরিচিত স্টাইলে ভিন্ন অনুভূতি।")}<br/>{t("দেখুন F-06-এর মূল বৈশিষ্ট্য।")}</p></div><div className="benefit-list"><article><Headphones/><div><h3>{t("তার ছাড়াই অডিও")}</h3><p>{t("ওয়্যারলেস স্টেরিও অডিওর সুবিধা, চশমার ফ্রেমেই।")}</p></div><span>{t("০১")}</span></article><article><Mic/><div><h3>{t("বিল্ট-ইন মাইক্রোফোন")}</h3><p>{t("অডিওর পাশাপাশি ফ্রেমে যুক্ত মাইক্রোফোন।")}</p></div><span>{t("০২")}</span></article><article><Glasses/><div><h3>{t("সহজ, মিনিমাল ডিজাইন")}</h3><p>{t("কালো ফ্রেম ও গাঢ় লেন্সের পরিচিত লুক।")}</p></div><span>{t("০৩")}</span></article></div></section>}
 {sections.gallery&&<section id="gallery" className="gallery-section"><div className="wrap section"><div className="section-heading"><div><p className="eyebrow">{t("কাছ থেকে দেখুন")}</p><h2>{t("ছবিতেই চিনে নিন আপনার F-06।")}</h2></div><p className="muted">{t("পণ্য ও প্যাকেজিংয়ের বাস্তব ছবি")}</p></div><div className="gallery-layout"><div><button className="gallery-main" onClick={()=>setZoom(true)} aria-label={photos[photo][1]+t(" — ছবি বড় করে দেখুন")}><img src={images['gallery'+photo]} alt={'F-06: '+photos[photo][1]} width="1600" height="900" loading="lazy"/><span className="zoom-label"><ZoomIn size={18}/>{t(" বড় করে দেখুন")}</span></button><div className="thumbnails" role="group" aria-label={t("পণ্যের ছবি নির্বাচন")}>{photos.map(([file,label],i)=><button key={file} className={i===photo?'selected':''} aria-label={label} aria-pressed={i===photo} onClick={()=>setPhoto(i)}><img src={images['gallery'+i]} alt="" width="100" height="65" loading="lazy"/></button>)}</div><p className="fine">{photos[photo][1]}{t(" · একই পণ্যের বিভিন্ন দিক")}</p></div><aside className="specs"><p className="eyebrow">{t("এক নজরে")}</p><h3>{t("পণ্যের তথ্য")}</h3><dl>{[[t("মডেল"),PRODUCT.id],[t("ধরন"),t('Wireless glasses')],[t("অডিও"),t('Wireless stereo')],[t("ওয়্যারলেস ভার্সন"),product.version],[t("মাইক্রোফোন"),t("বিল্ট-ইন")],[t("ব্যাটারি"),product.battery],[t("রং"),t("কালো")]].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><p className="fine">{t("কারিগরি তথ্য প্যাকেজিং অনুযায়ী। ব্যাটারির স্থায়িত্ব ও ডিভাইসের সঙ্গে সামঞ্জস্য জানতে যোগাযোগ করুন।")}</p><a className="inline-link" href={whatsapp()} target="_blank" rel="noopener noreferrer">{t("পণ্য সম্পর্কে জানতে চান? ")}<ArrowUpRight size={17}/></a></aside></div></div></section>}
 {sections.video&&<ProductVideo content={content}/>}{sections.steps&&<section className="wrap section steps"><div><p className="eyebrow">{t("অর্ডার করা সহজ")}</p><h2>{t("তিন ধাপেই আপনার অর্ডার।")}</h2></div><ol><li><span>{t("০১")}</span><h3>{t("আপনার তথ্য দিন")}</h3><p>{t("নাম, নম্বর ও বিস্তারিত ঠিকানা লিখুন।")}</p></li><li><span>{t("০২")}</span><h3>{t("অর্ডার জমা দিন")}</h3><p>{t("মোট মূল্য দেখে অর্ডার করুন। রেফারেন্সটি রাখুন।")}</p></li><li><span>{t("০৩")}</span><h3>{t("হাতে পেয়ে মূল্য দিন")}</h3><p>{t("ক্যাশ অন ডেলিভারিতে পণ্য গ্রহণ করুন।")}</p></li></ol></section>}
 <section id="checkout" ref={checkout} className="checkout-section"><div className="wrap checkout-grid"><div className="checkout-story"><p className="eyebrow">{t("আপনার F-06, এক ধাপ দূরে")}</p><h2>{t("স্টাইল বদলাক।")}<br/>{t("অর্ডার হোক সহজ।")}</h2><p>{t("পছন্দ হয়েছে? নিচের তথ্যগুলো দিন।")}<br/>{t("কোনো অগ্রিম পেমেন্ট লাগবে না।")}</p><img src={images.checkout} width="1600" height="900" loading="lazy" alt={t("F-06 ফ্রেমের ভেতরের অংশ")}/><div className="help"><Phone size={20}/><div><span>{t("অর্ডারে সাহায্য লাগলে কল করুন")}</span><a href={'tel:'+PRODUCT.phone}>{PRODUCT.phone}</a></div></div><button className="inline-link light" onClick={openHistory}><History size={18}/>{t(" এই ডিভাইসের অর্ডার দেখুন")}</button></div><form noValidate className="checkout-form" onSubmit={submit} onFocusCapture={trackStart}><div className="form-heading"><h2>{t("অর্ডার ফর্ম")}</h2><span><LockKeyhole size={16}/>{t(" ক্যাশ অন ডেলিভারি")}</span></div>{config.mode==='demo'&&<p className="demo-notice" role="status">{t("ডেমো চেকআউট — এখানে পরীক্ষামূলক অর্ডার হবে, বাস্তব ডেলিভারি হবে না।")}</p>}<div className="form-product"><img src={images.product} alt="" width="88" height="60"/><div><h3>{PRODUCT.name}</h3><p>{t("মডেল: F-06 · কালো · পরিমাণ: ১টি")}</p></div><strong>{t("{price}")}</strong></div>
 <label htmlFor="name">{t("সম্পূর্ণ নাম ")}<span aria-hidden="true">*</span></label><input id="name" name="name" autoComplete="name" maxLength={100} value={input.name} onChange={e=>setField('name',e.target.value)} placeholder={t("আপনার নাম লিখুন")} required aria-invalid={!!errors.name} aria-describedby={errors.name?'name-error':undefined}/>{errors.name&&<p className="field-error" id="name-error">{t(errors.name)}</p>}
 <label htmlFor="email">{t("ইমেইল ঠিকানা ")}<span aria-hidden="true">*</span></label><input id="email" name="email" type="email" autoComplete="email" maxLength={254} value={input.email} onChange={e=>setField('email',e.target.value)} placeholder="name@example.com" required aria-invalid={!!errors.email} aria-describedby={errors.email?'email-error':undefined}/>{errors.email&&<p className="field-error" id="email-error">{t(errors.email)}</p>}
 <label htmlFor="phone">{t("মোবাইল নম্বর ")}<span aria-hidden="true">*</span></label><input id="phone" name="phone" type="tel" inputMode="tel" autoComplete="tel-national" maxLength={20} value={input.phone} onChange={e=>setField('phone',e.target.value)} placeholder={t("০১XXXXXXXXX")} required aria-invalid={!!errors.phone} aria-describedby="phone-help phone-error"/><p id="phone-help" className="input-help">{t("বাংলা বা ইংরেজি অঙ্কে ১১ ডিজিটের নম্বর দিন।")}</p><p className="field-error" id="phone-error">{t(errors.phone)}</p>
 <label htmlFor="address">{t("বিস্তারিত ঠিকানা ")}<span aria-hidden="true">*</span></label><textarea id="address" name="address" autoComplete="street-address" rows={3} maxLength={600} value={input.address} onChange={e=>setField('address',e.target.value)} placeholder={t("বাসা/রোড, এলাকা, থানা ও জেলা")} required aria-invalid={!!errors.address} aria-describedby={errors.address?'address-error':undefined}/>{errors.address&&<p className="field-error" id="address-error">{t(errors.address)}</p>}
 <fieldset><legend>{t('ডেলিভারি')}</legend><div className="nationwide-delivery"><span><Truck size={18}/>{t('সারা বাংলাদেশ')}</span><strong>{money(delivery)}</strong></div><input type="hidden" name="area" value="bangladesh"/></fieldset>
 <div className="totals" aria-live="polite" aria-atomic="true"><div><span>{t("পণ্যের মূল্য (১টি)")}</span><span>{t("{price}")}</span></div><div><span>{t("ডেলিভারি চার্জ")}</span><span>{delivery!==undefined?money(delivery):t("এলাকা নির্বাচন করুন")}</span></div><div className="grand-total"><strong>{t("সর্বমোট")}</strong><strong>{total!==null?money(total):'—'}</strong></div></div><p className="cod-note"><PackageCheck size={18}/>{t(" পণ্য হাতে পেয়ে সম্পূর্ণ মূল্য পরিশোধ করুন।")}</p>{submitError&&<p className="error-banner" role="alert">{t(submitError)}</p>}<button className="btn submit" type="submit" disabled={submitting}>{submitting?t("অর্ডার সংরক্ষণ হচ্ছে…"):config.mode==='demo'?t("পরীক্ষামূলক অর্ডার দিন"):t("অর্ডার কনফার্ম করুন")}{submitting?<RefreshCw className="spin" size={19}/>:<ArrowRight size={20}/>}</button><p className="form-privacy">{t("আপনার তথ্য অর্ডার ও ডেলিভারির কাজে ব্যবহার করা হবে। ")}<button type="button" className="text-button" onClick={()=>setPolicy('privacy')}>{t("গোপনীয়তা নীতি")}</button></p></form></div></section>
 {sections.faq&&<section className="wrap section faq"><div><p className="eyebrow">{t("জেনে নিন")}</p><h2>{t("আপনার প্রশ্ন,")}<br/>{t("সহজ উত্তর।")}</h2><a className="inline-link" href={whatsapp()} target="_blank" rel="noopener noreferrer">{t("আরও জানতে WhatsApp করুন ")}<ArrowUpRight size={18}/></a></div><div>{[[t("মোট কত টাকা দিতে হবে?"),t("একটি পণ্যের অফার মূল্য {price}। সারা বাংলাদেশে ডেলিভারি {deliveryFee}। ডেলিভারিসহ সর্বমোট {orderTotal}।")],[t("আগে কি কোনো টাকা দিতে হবে?"),t("না। এই চেকআউটে ক্যাশ অন ডেলিভারি সুবিধা রয়েছে। পণ্য হাতে পেয়ে সম্পূর্ণ মূল্য পরিশোধ করবেন।")],[t("অর্ডারের অবস্থা কীভাবে জানব?"),t("“এই ডিভাইসের অর্ডার” থেকে সর্বশেষ অবস্থা দেখুন। একই ব্রাউজার ব্যবহার করুন। প্রয়োজনে অর্ডার রেফারেন্স দিয়ে ফোন বা WhatsApp-এ যোগাযোগ করুন।")],[t("কত দিনে ডেলিভারি হবে? রিটার্ন করা যাবে?"),t("ডেলিভারির সময়সীমা এবং রিটার্ন বা এক্সচেঞ্জের শর্ত জানতে অর্ডারের আগে আমাদের সঙ্গে যোগাযোগ করুন।")],[t("ব্যাটারি কতক্ষণ চলে? আমার ফোনে কাজ করবে?"),t("প্যাকেজিংয়ে 80mAh ব্যাটারি ও Wireless V5.4 উল্লেখ আছে। ব্যবহারের সময়সীমা এবং আপনার ফোনের সঙ্গে সামঞ্জস্য নিশ্চিত করতে যোগাযোগ করুন।")]].map(([q,a])=><details key={q}><summary>{q}<ChevronRight size={19}/></summary><p>{a}</p></details>)}</div></section>}
 </main><footer><div className="wrap footer-grid"><div><a className="brand" href="/"><Glasses size={28}/><span>{product.brand}<span>{PRODUCT.name} · {PRODUCT.id}</span></span></a><p>{t("চশমা পরুন। প্রিয় গানও শুনুন।")}</p></div><div><h3>{t("কথা বলুন")}</h3><a href={'tel:'+PRODUCT.phone}>{PRODUCT.phone}</a><div className="footer-social"><a href={whatsapp()} target="_blank" rel="noopener noreferrer">WhatsApp <ArrowUpRight size={14}/></a><a href={PRODUCT.facebook} target="_blank" rel="noopener noreferrer">Facebook <ArrowUpRight size={14}/></a></div></div><div><h3>{t("প্রয়োজনীয় তথ্য")}</h3><button onClick={openHistory}>{t("এই ডিভাইসের অর্ডার")}</button><button onClick={()=>setPolicy('delivery')}>{t("ডেলিভারি ও রিটার্ন")}</button><button onClick={()=>setPolicy('privacy')}>{t("গোপনীয়তা নীতি")}</button>{config.pixelId&&<button onClick={()=>setConsentOpen(true)}>{t("ট্র্যাকিং পছন্দ")}</button>}</div></div><div className="wrap footer-bottom"><span>{PRODUCT.name} · {PRODUCT.id}</span><span>{t("মূল্য বাংলাদেশি টাকায় (৳)")}</span></div></footer>
 {!checkoutVisible&&!zoom&&!historyOpen&&!order&&!policy&&!consentOpen&&<div className="mobile-bar"><div><strong>{t("{price}")}</strong><span>{t("ডেলিভারি চার্জ প্রযোজ্য")}</span></div><a className="btn small" href="#checkout" onClick={trackStart}>{t("অর্ডার করুন ")}<ArrowUpRight size={18}/></a></div>}
 <Modal open={zoom} onClose={()=>setZoom(false)} title={photos[photo][1]} description={t("F-06 পণ্যের বাস্তব ছবি")} wide><img className="zoom-image" src={images['gallery'+photo]} alt={'F-06: '+photos[photo][1]}/></Modal>
 <Modal open={!!order} onClose={()=>setOrder(null)} title={order?.demo?t("পরীক্ষামূলক অর্ডার সংরক্ষিত"):t("আপনার অর্ডার গ্রহণ করা হয়েছে")} description={order?.demo?t("এটি ডেমো অর্ডার। এর জন্য ডেলিভারি বা পেমেন্ট হবে না।"):t("অর্ডার রেফারেন্সটি রাখুন। পণ্য হাতে পেয়ে মূল্য পরিশোধ করবেন।")}>{order&&<><div className="success-icon"><Check size={28}/></div><label htmlFor="order-reference" className="fine">{t("অর্ডার রেফারেন্স")}</label><div className="reference-row"><input id="order-reference" value={order.reference} readOnly/><button aria-label={t("অর্ডার রেফারেন্স কপি করুন")} onClick={copyReference}>{copied?<Check size={18}/>:<Copy size={18}/>}</button></div><p role="status" className="fine">{copied?t("রেফারেন্স কপি হয়েছে।"):t(copyError)}</p><div className="confirmation-summary"><p>{t("Glasses Wireless headset · F-06 · ১টি")}</p><div><span>{t("পণ্যের মূল্য")}</span><strong>{money(order.subtotal)}</strong></div><div><span>{t("ডেলিভারি")}</span><strong>{money(order.delivery)}</strong></div><div><span>{t("সর্বমোট")}</span><strong>{money(order.total)}</strong></div><p>{t("পেমেন্ট: ক্যাশ অন ডেলিভারি · বকেয়া")}</p></div>{storageWarning&&<p className="error-banner">{t(storageWarning)}</p>}{!order.demo&&<a className="btn" href={whatsapp(order)} target="_blank" rel="noopener noreferrer"><MessageCircle size={20}/>{t(" WhatsApp-এ অর্ডার কনফার্ম করুন")}</a>}{!order.demo&&<p className="fine">{t("WhatsApp যোগাযোগ ঐচ্ছিক। বোতামটি কথোপকথন খুলবে; মেসেজ আপনাকে পাঠাতে হবে।")}</p>}<button className="outline-btn" onClick={()=>{setOrder(null);openHistory()}}>{t("অর্ডারের অবস্থা দেখুন")}</button></>}</Modal>
 <Modal open={historyOpen} onClose={()=>setHistoryOpen(false)} title={t("এই ডিভাইসের অর্ডার")} description={t("একই ব্রাউজারে সংরক্ষিত অর্ডার। ব্রাউজারের তথ্য মুছে ফেললে এই তালিকাও মুছে যাবে।")} wide>{historyError&&<p role="alert" className="error-banner">{t(historyError)}</p>}{orders.length===0?<div className="empty"><PackageCheck size={38}/><p>{t("এখনো কোনো অর্ডার নেই।")}</p><button className="btn" onClick={()=>{setHistoryOpen(false);checkout.current?.scrollIntoView()}}>{t("অর্ডার দিন")}</button></div>:<><div className="order-list">{orders.map(v=><article key={v.reference}><div className="history-top"><strong>{v.reference}</strong><span className="status">{t(statuses[v.status]||v.status)}</span></div><p>{t("F-06 · ১টি · ")}{money(v.total)} {v.demo?t("· ডেমো অর্ডার"):''}</p><p className="fine">{t("অর্ডারের সময়: ")}{date(v.createdAt)}<br/>{t("শেষ দেখা: ")}{date(v.syncedAt)}{t(" · পেমেন্ট: ")}{v.paymentStatus==='paid'?t("পরিশোধিত"):t("বকেয়া")}</p><div className="history-actions"><button className="outline-btn" disabled={!!refreshing} onClick={()=>refresh(v)}><RefreshCw size={16} className={refreshing===v.reference?'spin':''}/>{refreshing===v.reference?t("আপডেট হচ্ছে…"):t("সর্বশেষ অবস্থা")}</button>{!v.demo&&<a href={whatsapp(v)} target="_blank" rel="noopener noreferrer">{t("সহায়তা ")}<ArrowUpRight size={15}/></a>}</div></article>)}</div><button className="text-button clear-history" onClick={()=>{try{localStorage.removeItem(storageKey);setOrders([])}catch{setHistoryError(t("হিস্ট্রি মুছতে পারিনি। ব্রাউজারের সেটিংস থেকে মুছতে পারেন।"))}}}>{t("এই ডিভাইসের হিস্ট্রি মুছুন")}</button><p className="fine">{t("হিস্ট্রি মুছলে সংরক্ষিত অর্ডার বাতিল হবে না।")}</p></>}</Modal>
 <Modal open={!!policy} onClose={()=>setPolicy(null)} title={policy==='privacy'?t("আপনার তথ্যের গোপনীয়তা"):t("ডেলিভারি ও রিটার্ন")} description={policy==='privacy'?t("অর্ডারের প্রয়োজনীয় তথ্য যত্নের সঙ্গে ব্যবহার করা হয়।"):t("অর্ডারের আগে প্রয়োজনীয় শর্ত জেনে নিন।")}>{policy==='privacy'?<div className="policy-copy"><p>{t("অর্ডার পরিচালনা ও ডেলিভারির জন্য আপনার নাম, মোবাইল নম্বর, ঠিকানা এবং অর্ডারের বিবরণ সার্ভারে সংরক্ষণ করা হয়। অনুমোদিত বিক্রেতা অর্ডার পরিচালনার জন্য এই তথ্য দেখতে পারেন।")}</p><p>{t("এই ডিভাইসে অর্ডার রেফারেন্স, সীমিত সারাংশ ও নিরাপদ প্রবেশ টোকেন থাকে। নাম, ফোন বা ঠিকানা ডিভাইসের অর্ডার হিস্ট্রিতে রাখা হয় না। শেয়ার করা ডিভাইসে কাজ শেষে হিস্ট্রি মুছে দিন।")}</p><p>{t("বিজ্ঞাপনের কার্যকারিতা বোঝার জন্য প্রচারের UTM তথ্য অর্ডারের সঙ্গে রাখা হয়। Meta Pixel চালু থাকলে আপনার সম্মতি নিয়ে page view ও checkout/order event পাঠানো হবে। নাম, ফোন ও ঠিকানা Pixel-এ পাঠানো হয় না।")}</p><p>{t("নিজের তথ্য সম্পর্কে জানতে বা মুছে দেওয়ার অনুরোধ করতে ")}<a href={'tel:'+PRODUCT.phone}>{PRODUCT.phone}</a>{t(" নম্বরে যোগাযোগ করুন।")}</p></div>:<div className="policy-copy"><p>{t("সারা বাংলাদেশে ডেলিভারি {deliveryFee}। পণ্যের মূল্যসহ মোট টাকা পণ্য হাতে পেয়ে পরিশোধ করবেন।")}</p><p>{t("ডেলিভারির সময়সীমা, রিটার্ন, এক্সচেঞ্জ ও প্রযোজ্য শর্ত জানতে অর্ডারের আগে যোগাযোগ করুন।")}</p><a className="btn" href={whatsapp()} target="_blank" rel="noopener noreferrer">{t("WhatsApp-এ বিস্তারিত জানুন ")}<ArrowUpRight size={18}/></a></div>}</Modal>
 {consentOpen&&<aside className="tracking-bar" aria-label={t('বিজ্ঞাপনের অনুমতি')}><span>{t('বিজ্ঞাপনের অনুমতি?')}</span><button type="button" onClick={()=>allowTracking(true)}>{t('হ্যাঁ')}</button><button type="button" onClick={()=>allowTracking(false)}>{t('না')}</button></aside>}
 </>;
}




