import { cleanCampaign, PRODUCT, type SavedOrder } from './product';
type Pixel = ((...args:any[])=>void)&{callMethod?:(...args:any[])=>void;queue:any[];push:any;loaded:boolean;version:string};
declare global {interface Window { fbq?:Pixel; _fbq?:Pixel }}
let ready:Promise<boolean>|null=null, checkoutSent=false,viewSent=false,pageSent=false;
export function readCampaign(){let cached={};try{cached=JSON.parse(sessionStorage.getItem('f06_campaign')||'{}')}catch{}const params=new URLSearchParams(location.search);const inbound=cleanCampaign(Object.fromEntries(params));const campaign=Object.keys(inbound).length?inbound:cleanCampaign(cached);try{sessionStorage.setItem('f06_campaign',JSON.stringify(campaign))}catch{}if(location.search)history.replaceState(history.state,'',location.pathname+location.hash);return campaign;}
export function consent(){try{return localStorage.getItem('f06_tracking')==='yes'}catch{return false}}
export function setConsent(allow:boolean){try{localStorage.setItem('f06_tracking',allow?'yes':'no')}catch{}window.fbq?.('consent',allow?'grant':'revoke');}
export function initPixel(id:string):Promise<boolean>{if(!id||!consent())return Promise.resolve(false);if(ready)return ready;ready=new Promise(resolve=>{const fb=(function(...args:any[]){if(fb.callMethod)fb.callMethod(...args);else fb.queue.push(args)}) as Pixel;fb.queue=[];fb.push=fb;fb.loaded=true;fb.version='2.0';window.fbq=fb;window._fbq=fb;fb('consent','grant');fb('set','autoConfig',false,id);fb('init',id);const script=document.createElement('script');script.async=true;script.src='https://connect.facebook.net/en_US/fbevents.js';script.onload=()=>resolve(true);script.onerror=()=>resolve(false);document.head.appendChild(script);});return ready;}
export async function pageEvent(id:string){if(await initPixel(id)&&consent()&&!pageSent){pageSent=true;window.fbq?.('track','PageView');}}
export async function viewEvent(id:string,price:number=PRODUCT.price,productId:string=PRODUCT.id){if(await initPixel(id)&&consent()&&!viewSent){viewSent=true;window.fbq?.('track','ViewContent',{content_ids:[productId],content_type:'product',value:price,currency:'BDT'});}}
export async function checkoutEvent(id:string,price:number=PRODUCT.price,productId:string=PRODUCT.id){if(await initPixel(id)&&consent()&&!checkoutSent){checkoutSent=true;window.fbq?.('track','InitiateCheckout',{content_ids:[productId],content_type:'product',num_items:1,value:price,currency:'BDT'});}}
export async function purchaseEvent(id:string,order:SavedOrder){try{if(order.demo||!await initPixel(id)||!consent())return;const response=await fetch('/api/orders/event',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+order.token},body:JSON.stringify({reference:order.reference})});if(!response.ok)return;const event=await response.json() as {granted:boolean;eventId:string;value:number};if(event.granted&&consent())window.fbq?.('track','Purchase',{content_ids:[PRODUCT.id],content_type:'product',num_items:1,value:event.value,currency:'BDT'},{eventID:event.eventId});}catch{/* Analytics never blocks a saved order. */}}


